# Generated by Django 4.1 on 2024-10-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_family_user_family_alter_child_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="quote",
            name="end_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="end_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="quotes_images/"),
        ),
        migrations.AddField(
            model_name="quote",
            name="start_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="start_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
