# Generated by Django 4.1 on 2024-10-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_quote_category_quote_end_day_quote_end_month_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="end_day",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="end_month",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="end_year",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="start_day",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="start_month",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="start_year",
        ),
        migrations.AddField(
            model_name="quote",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
