# Generated by Django 4.1 on 2024-10-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_quote_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_first_login",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
