# Generated by Django 4.1 on 2024-10-20 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_family_invite_url_alter_user_family"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="invite_url",
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
