# Generated by Django 4.1 on 2024-10-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_family_invite_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="user",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="family",
            name="invite_url",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
