# Generated by Django 4.1 on 2024-10-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
