# Generated by Django 4.1 on 2024-10-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_quote_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="invite_url",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
