# Generated by Django 4.1 on 2024-10-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_family_invite_url_alter_quote_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_first_login",
            field=models.BooleanField(default=True),
        ),
    ]
